index:
    path: /
    controller: App\Controller\FrontController::index

aboutme:
    path: /aboutme
    controller: App\Controller\FrontController::aboutme

works:
    path: /works
    controller: App\Controller\FrontController::works

contact:
    path: /contact
    controller: App\Controller\FrontController::contact
