vich_uploader:
    db_driver: orm

    mappings:
        imgWorks_asset:
            uri_prefix: '%app.path.imgWorks_asset%'
            upload_destination: '%kernel.project_dir%/public%app.path.imgWorks_asset%'
        imgBigWorks_asset:
            uri_prefix: '%app.path.imgBigWorks_asset%'
            upload_destination: '%kernel.project_dir%/public%app.path.imgBigWorks_asset%'
