index:
    path: /{_locale}
    controller: App\Controller\FrontController::index
    locale:      fr
    requirements:
      _locale: '%locales_requirements%'

aboutme:
    path: /aboutme/{_locale}/
    controller: App\Controller\FrontController::aboutme
    requirements:
      _locale: '%locales_requirements%'

aboutmeCV:
    path: /aboutmeCV/{_locale}
    controller: App\Controller\FrontController::aboutmeCV
    requirements:
      _locale: '%locales_requirements%'

frontWorks:
    path: /frontWorks/{_locale}
    controller: App\Controller\FrontController::frontWorks
    requirements:
      _locale: '%locales_requirements%'

worksWeb:
    path: /works/web/{_locale}
    controller: App\Controller\FrontController::worksWeb
    requirements:
      _locale: '%locales_requirements%'

worksGraf:
    path: /works/Graf/{_locale}
    controller: App\Controller\FrontController::worksGraf
    requirements:
      _locale: '%locales_requirements%'

contact:
    path: /contact/{_locale}
    controller: App\Controller\FrontController::contact
    requirements:
      _locale: '%locales_requirements%'

mentions:
    path: /mentions/{_locale}
    controller: App\Controller\FrontController::mentions
    requirements:
      _locale: '%locales_requirements%'

booking_calendar:
    path: /booking/calendar/{_locale}
    controller: App\Controller\BookingController::calendar
    requirements:
      _locale: '%locales_requirements%'
