index:
    path: /
    controller: App\Controller\FrontController::index

aboutme:
    path: /aboutme
    controller: App\Controller\FrontController::aboutme

aboutmeCV:
    path: /aboutmeCV
    controller: App\Controller\FrontController::aboutmeCV

worksFront:
    path: /worksFront
    controller: App\Controller\FrontController::worksFront

worksWeb:
    path: /works/web
    controller: App\Controller\FrontController::worksWeb

worksGraf:
    path: /works/Graf
    controller: App\Controller\FrontController::worksGraf

contact:
    path: /contact
    controller: App\Controller\FrontController::contact

mentions:
    path: /mentions
    controller: App\Controller\FrontController::mentions
